site_name: AutoBaby
repo_url: https://github.com/Quiet-zh/AutoBaby
site_url: https://Quiet-zh.github.io/AutoBaby
site_description: A Python automation application for Windows 10+ featuring auto-click, simulated clicks, scheduled tasks, API requests, and a native GUI, managed with Poetry.
site_author: ohmyrain
edit_uri: edit/main/docs/
repo_name: Quiet-zh/AutoBaby
copyright: Maintained by <a href="https://Quiet-zh.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Quiet-zh/AutoBaby
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/AutoBaby

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
