# 关于我Cookiecutter-Poetry模板创建的这个项目，需要编写类似于main.py的入口文件并且在配置文件中定义吗
[tool.poetry]
name = "autobaby"
version = "0.0.1"
description = "A Python automation application for Windows 10+ featuring auto-click, simulated clicks, scheduled tasks, API requests, and a native GUI, managed with Poetry."
authors = ["ohmyrain <2013471393@qq.com>"]
repository = "https://github.com/Quiet-zh/AutoBaby"
documentation = "https://Quiet-zh.github.io/AutoBaby/"
readme = "README.md"
packages = [
  {include = "autobaby"}
]

[tool.poetry.scripts]
autobaby = "autobaby.gui:create_window"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pyautogui = "^0.9.54"
schedule = "^1.2.2"
requests = "^2.32.3"
loguru = "^0.7.3"
pyyaml = "^6.0.2"
pyqt6 = "^6.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
deptry = "^0.16.2"
pyright = "^1.1.382"
pre-commit = "^3.4.0"
tox = "^4.11.1"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^9.2.7"
mkdocstrings = {extras = ["python"], version = "^0.26.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.pyright]
include = ["autobaby"]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["autobaby"]


[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
